<script src="{{ asset('./backend/js/jquery-3.6.0.min.js') }}"></script>
<script src="{{ asset('./backend/js/tom-select.complete.min.js') }}"></script>
<script src="{{ asset('./backend/js/moment.min.js') }}"></script>
<script src="{{ asset('./backend/js/axios.min.js') }}"></script>
<script src="{{ asset('./backend/js/simplebar.min.js') }}"></script>
{{-- <script src="{{ asset('./backend/js/overlayscrollbars.browser.es6.min.js') }}"></script> --}}
{{-- <script src="{{ asset('./backend/plugins/apexcharts-bundle/js/apexcharts.min.js') }}"></script>
<script src="{{ asset('./backend/js/ckeditor.js') }}"></script>
<script src="{{ asset('./backend/js/apex.js') }}"></script> 
<script src="{{ asset('./backend/js/dropify.js') }}"></script> --}}
<script src="{{ asset('./backend/js/chart.min.js') }}"></script>
<script src="{{ asset('./backend/js/chart_codes.js') }}"></script>
<script src="{{ asset('./backend/js/custom.js') }}"></script>